const clubs = [
  {
    _id: "1",
    value: "castlefordtigers",
    label: "Castleford Tigers",
    initials: "CT",
    sport: "rugby",
    playingDesignBreak: "rectangle",
    tshirtDesignBreak: "no",
    numberBreak: "yes",
    color1: "#ff8300",
    color1Ref: 11,
    color2: "#000000",
    color2Ref: 0,
    color3: "#ffffff",
    color3Ref: 1,
    alllogo1: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "red",
    },

    playinglogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "red",
    },

    playinglogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo7: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "white",
      yellow: "white",
      orange: "orange",
      green: "black",
      red: "orange",
    },

    playinglogo8: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo9: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "red",
      pink: "red",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "red",
    },
    shortslogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "white",
      yellow: "white",
      orange: "orange",
      green: "black",
      red: "orange",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "80mm x 80mm",
    proLogo2Size: "75mm x 60mm",
    proLogo3Size: "45.4mm x 55mm",
    proLogo4Size: "109mm x 28.9mm",
    proLogo5Size: "109mm x 28.9mm",
    proLogo6Size: "275mm x 109mm",
    proLogo7Size: "90.7mm x 35.2mm",
    proLogo8Size: "240mm x 66mm",
    proLogo9Size: "310mm x 63.8mm",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "123mm x 58mm",
    proLogo13Size: "120mm x 50mm",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "100mm x 60mm",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "45.4mm x 55mm",
    outerLogo4Size: "NO LOGO",
    shortsLogo2Size: "170mm x 57mm",
    shortsLogo3Size: "305mm x 64.9mm",
    shortsLogo4Size: "160mm x 62mm",
    shortsLogo5Size: "160mm x 62mm",
  },
  {
    _id: "2",
    value: "englandrl",
    label: "England RL",
    initials: "ERL",
    sport: "rugby",
    playingDesignBreak: "thin",
    tshirtDesignBreak: "no",
    numberBreak: "yes",
    color1: "#ffffff",
    color1Ref: 1,
    color2: "#ce0e2d",
    color2Ref: 12,
    color3: "#9d9d9c",
    color3Ref: 2,
    alllogo1: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo8: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo9: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "green",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "53mm x 100mm",
    proLogo2Size: "45.4mm x 55mm",
    proLogo3Size: "NO LOGO",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "350mm x 57.9mm",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "286mm x 47.8mm",
    proLogo9Size: "307mm x 70mm",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "NO LOGO",
    proLogo13Size: "120mm x 120mm",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "NO LOGO",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "45.4mm x 55mm",
    outerLogo4Size: "NO LOGO",
    shortsLogo2Size: "49.5mm x 60mm",
    shortsLogo3Size: "NO LOGO",
    shortsLogo4Size: "200mm x 33.4mm",
    shortsLogo5Size: "136mm x 58mm",
  },
  {
    _id: "3",
    value: "gloucester",
    label: "Gloucester Rugby",
    initials: "GR",
    sport: "rugby",
    playingDesignBreak: "no",
    tshirtDesignBreak: "no",
    numberBreak: "no",
    color1: "#ce0e2d",
    color1Ref: 12,
    color2: "#ffffff",
    color2Ref: 1,
    color3: "#53575a",
    color3Ref: 17,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "red",
      green: "black",
      red: "red",
    },
    playinglogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "red",
      green: "black",
      red: "red",
    },
    playinglogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo8: {
      white: "white",
      black: "black",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo9: {
      white: "white",
      black: "black",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo10: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "69mm x 80mm",
    proLogo2Size: "45.4mm x 55mm",
    proLogo3Size: "NO LOGO",
    proLogo4Size: "102mm x 57mm",
    proLogo5Size: "102mm x 57mm",
    proLogo6Size: "NO LOGO",
    proLogo7Size: "NO LOGO",
    proLogo8Size:
      "Item Repeated, each logo to be;                                   SIZE M - 159mm(W) x 58mm(H)         SIZE L - 159mm(W) x 58mm(H)        SIZE XL - 165mm(W) x 60mm(H)        SIZE 2XL - 172mm(W) x 63mm(H)        SIZE 3XL - 178mm(W) x 65mm(H)        SIZE 4XL - 192mm(W) x 70mm(H)        SIZE 5XL - 198mm(W) x 72mm(H)",
    proLogo9Size:
      "SIZE M - 214mm(W) x 78mm(H)         SIZE L - 219mm(W) x 80mm(H)        SIZE XL - 230mm(W) x 84mm(H)        SIZE 2XL - 247mm(W) x 90mm(H)        SIZE 3XL -    260mm(W) x 95mm(H)         SIZE 4XL - 260mm(W) x 95mm(H)        SIZE 5XL - 260mm(W) x 95mm(H)",
    proLogo10Size: "331mm(W) x 87mm(H)",
    proLogo11Size: "305mm x 205mm",
    proLogo12Size: "NO LOGO",
    proLogo13Size: "NO LOGO",
    proLogo14Size: "102mm x 16mm",
    proLogo15Size: "102mm x 120mm",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "45.4mm x 55mm",
    outerLogo4Size: "NO LOGO",
    shortsLogo2Size: "46.9mm x 55mm",
    shortsLogo3Size: "259mm x 68mm",
    shortsLogo4Size: "NO LOGO",
    shortsLogo5Size: "NO LOGO",
  },
  {
    _id: "4",
    value: "hullkr",
    label: "Hull KR",
    initials: "HKR",
    sport: "rugby",
    playingDesignBreak: "no",
    tshirtDesignBreak: "no",
    numberBreak: "yes",
    color1: "#ce0e2d",
    color1Ref: 12,
    color2: "#ffffff",
    color2Ref: 1,
    color3: "#1c355e",
    color3Ref: 4,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo8: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo9: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "yellow",
      green: "black",
      red: "black",
    },
    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo13: {
      white: "white",
      black: "white",
      blue: "red",
      purple: "red",
      pink: "red",
      yellow: "white",
      orange: "white",
      green: "red",
      red: "red",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "black",
      blue: "blue",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "blue",
      red: "black",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "56.5mm x 80mm",
    proLogo2Size: "45.4mm x 55mm",
    proLogo3Size: "NO LOGO",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "NO LOGO",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "200.8mm x 79mm",
    proLogo9Size: "296.7mm x 67mm",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "123mm x 58mm",
    proLogo13Size: "131.4mm x 44mm",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "96.1mm x 61.5mm",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "45.4mm x 55mm",
    outerLogo4Size: "NO LOGO",
    shortsLogo2Size: "150mm x 66.2mm",
    shortsLogo3Size: "331mm x 60.2mm",
    shortsLogo4Size: "115.1mm x 86.82mm",
    shortsLogo5Size: "58mm x 70mm",
  },
  {
    _id: "5",
    value: "leedsrhinos",
    label: "Leeds Rhinos",
    initials: "LR",
    sport: "rugby",
    playingDesignBreak: "square",
    tshirtDesignBreak: "square",
    numberBreak: "yes",
    color1: "#004a98",
    color1Ref: 3,
    color2: "#ffc629",
    color2Ref: 9,
    color3: "#ffffff",
    color3Ref: 1,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "yellow",
      green: "black",
      red: "black",
    },
    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo8: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo9: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo13: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "green",
      red: "black",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "green",
      red: "black",
    },

    traininglogo13: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "green",
      red: "black",
    },
    traininglogo15: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "green",
      red: "black",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "yellow",
      green: "black",
      red: "black",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "yellow",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "yellow",
      green: "black",
      red: "black",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "101mm x 70mm",
    proLogo2Size: "103mm x 42mm",
    proLogo3Size: "45.4mm x 55mm",
    proLogo4Size: "102.9mm x 31.58mm",
    proLogo5Size: "102.9mm x 31.58mm",
    proLogo6Size: "160mm x 177mm",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "186.6mm x 85.7mm",
    proLogo9Size: "152mm x 130mm",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "123mm x 58mm",
    proLogo13Size: "157.9mm x 36mm",
    proLogo14Size: "82.7mm x 74mm",
    proLogo15Size: "157.9mm x 36mm",
    trainingLogo13Size: "157.9mm x 36mm",
    trainingLogo15Size: "157.9mm x 36mm",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "160mm x 177mm",
    outerLogo2Size: "72mm x 80mm",
    outerLogo4Size: "80mm x 19.8mm",
    shortsLogo2Size: "45.4mm x 55mm",
    shortsLogo3Size: "NO LOGO",
    shortsLogo4Size: "94.6mm x 105mm",
    shortsLogo5Size: "105mm x 94mm",
  },
  {
    _id: "6",
    value: "doncasterbelles",
    label: "Doncaster Belles",
    initials: "DB",
    sport: "football",
    playingDesignBreak: "rectangle",
    tshirtDesignBreak: "no",
    numberBreak: "yes",
    color1: "#ce0e2d",
    color1Ref: 12,
    color2: "#ffffff",
    color2Ref: 1,
    color3: "#53575a",
    color3Ref: 17,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "red",
      pink: "red",
      yellow: "white",
      orange: "red",
      green: "white",
      red: "red",
    },

    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo8: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo9: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "yellow",
      orange: "yellow",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "88.7mm x 70mm",
    proLogo2Size: "45.4mm x 55mm",
    proLogo3Size: "NO LOGO",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "247mm x 95mm",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "NO LOGO",
    proLogo9Size: "NO LOGO",
    proLogo10Size: "90mm x 17.5mm",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "NO LOGO",
    proLogo13Size: "NO LOGO",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "NO LOGO",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "45.4mm x 55mm",
    outerLogo4Size: "NO LOGO",
    shortsLogo2Size: "45.4mm x 55mm",
    shortsLogo3Size: "NO LOGO",
    shortsLogo4Size: "NO LOGO",
    shortsLogo5Size: "NO LOGO",
  },
  {
    _id: "7",
    value: "doncasterrovers",
    label: "Doncaster Rovers",
    initials: "DR",
    sport: "football",
    playingDesignBreak: "rectangle",
    tshirtDesignBreak: "no",
    numberBreak: "yes",
    color1: "#ce0e2d",
    color1Ref: 12,
    color2: "#ffffff",
    color2Ref: 1,
    color3: "#53575a",
    color3Ref: 17,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "yellow",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo8: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo9: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "88.7mm x 70mm",
    proLogo2Size: "45.4mm x 55mm",
    proLogo3Size: "NO LOGO",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "210mm x 95mm",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "185mm x 51.8mm",
    proLogo9Size: "NO LOGO",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "NO LOGO",
    proLogo13Size: "NO LOGO",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "NO LOGO",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "45.4mm x 55mm",
    outerLogo4Size: "NO LOGO",
    shortsLogo2Size: "45.4mm x 55mm",
    shortsLogo3Size: "NO LOGO",
    shortsLogo4Size: "NO LOGO",
    shortsLogo5Size: "216mm x 46mm",
  },
  {
    _id: "8",
    value: "doncasterrlfc",
    label: "Doncaster RLFC",
    initials: "DONS",
    sport: "rugby",
    playingDesignBreak: "rectangle",
    tshirtDesignBreak: "no",
    numberBreak: "yes",
    color1: "#004a98",
    color1Ref: 3,
    color2: "#ffc629",
    color2Ref: 9,
    color3: "#ffffff",
    color3Ref: 1,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "red",
      blue: "white",
      purple: "red",
      pink: "red",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "red",
    },

    playinglogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo8: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo9: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "66.95mm x 73mm",
    proLogo2Size: "67mm x 66.8mm",
    proLogo3Size: "45.4mm x 55mm",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "327mm x 90mm",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "234.3mm x 68mm",
    proLogo9Size: "100.9mm x 140mm",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "117mm x 52.4mm",
    proLogo13Size: "94.3mm x 62mm",
    proLogo14Size: "96.8mm x 62mm",
    proLogo15Size: "122.9mm x 48.79mm",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "45.4mm x 55mm",
    outerLogo4Size: "NO LOGO",
    shortsLogo2Size: "45.4mm x 55mm",
    shortsLogo3Size: "254mm x 78.7mm",
    shortsLogo4Size: "NO LOGO",
    shortsLogo5Size: "NO LOGO",
  },
  {
    _id: "9",
    value: "sheffieldeagles",
    label: "Sheffield Eagles",
    initials: "SE",
    sport: "rugby",
    playingDesignBreak: "rectangle",
    tshirtDesignBreak: "rectangle",
    numberBreak: "yes",
    color1: "#ce0e2d",
    color1Ref: 12,
    color2: "#d0af21",
    color2Ref: 19,
    color3: "#ffffff",
    color3Ref: 1,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo7: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo8: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo9: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo14: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo15: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "red",
      purple: "white",
      pink: "red",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "red",
    },

    outerlogo2: {
      white: "white",
      black: "white",
      blue: "red",
      purple: "white",
      pink: "red",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "red",
    },
    outerlogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "orange",
      yellow: "orange",
      orange: "orange",
      green: "white",
      red: "orange",
    },
    shortslogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "70mm x 80mm",
    proLogo2Size: "71mm x 62.3mm",
    proLogo3Size: "45.4mm x 55mm",
    proLogo4Size: "110mm x 28.6mm",
    proLogo5Size: "110mm x 28.6mm",
    proLogo6Size: "237mm x 126mm",
    proLogo7Size: "144.6mm x 22.12mm",
    proLogo8Size: "200.2mm x 79.9mm",
    proLogo9Size: "273.3mm x 73.16mm",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "117mm x 52.4mm",
    proLogo13Size: "78.6mm x 76.23mm",
    proLogo14Size: "140.8mm x 42.61mm",
    proLogo15Size: "78.6mm x 76.23mm",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "237mm x 126mm",
    outerLogo2Size: "114mm x 60mm",
    outerLogo4Size: "80mm x 19.8mm",
    shortsLogo2Size: "45.4mm x 55mm",
    shortsLogo3Size: "322mm x 62mm",
    shortsLogo4Size: "136.3mm x 73.32mm",
    shortsLogo5Size: "215mm x 46.4mm",
  },
  {
    _id: "10",
    value: "widnesvikings",
    label: "Widnes Vikings",
    initials: "WV",
    sport: "rugby",
    playingDesignBreak: "rectangle",
    tshirtDesignBreak: "thin",
    numberBreak: "yes",
    color1: "#000000",
    color1Ref: 0,
    color2: "#ffffff",
    color2Ref: 1,
    color3: "#9d9d9c",
    color3Ref: 2,
    alllogo1: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo7: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo8: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo9: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo14: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    shortslogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "85mm x 67mm",
    proLogo2Size: "67mm x 67mm",
    proLogo3Size: "45.4mm x 55mm",
    proLogo4Size: "101.8mm x 31.39mm",
    proLogo5Size: "101.8mm x 31.39mm",
    proLogo6Size: "330mm x 74.84mm",
    proLogo7Size: "101.4mm x 31mm",
    proLogo8Size: "300mm x 53.33mm",
    proLogo9Size: "330mm x 36.7mm",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "117mm x 52.4mm",
    proLogo13Size: "110.83mm x 54mm",
    proLogo14Size: "52.2mm x 50mm",
    proLogo15Size: "90mm x 66.59mm",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "310mm x 55mm",
    outerLogo2Size: "120mm x 21mm",
    outerLogo4Size: "80mm x 19.8mm",
    shortsLogo2Size: "NO LOGO",
    shortsLogo3Size: "241.5mm x 81mm",
    shortsLogo4Size: "1NO LOGO",
    shortsLogo5Size: "45.4mm x 55mm",
  },
  {
    _id: "11",
    value: "westbrom",
    label: "West Bromwich Albion",
    initials: "WB",
    sport: "football",
    playingDesignBreak: "no",
    tshirtDesignBreak: "no",
    numberBreak: "no",
    color1: "#1c355e",
    color1Ref: 4,
    color2: "#ffffff",
    color2Ref: 1,
    color3: "#ce0e2d",
    color3Ref: 12,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo8: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo9: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    outerlogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    shortslogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "67mm x 80mm",
    proLogo2Size: "NO LOGO",
    proLogo3Size: "NO LOGO",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "NO LOGO",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "NO LOGO",
    proLogo9Size: "NO LOGO",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "NO LOGO",
    proLogo13Size: "NO LOGO",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "NO LOGO",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "NO LOGO",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "NO LOGO",
    outerLogo4Size: "NO LOGO",
    shortsLogo2Size: "NO LOGO",
    shortsLogo3Size: "NO LOGO",
    shortsLogo4Size: "1NO LOGO",
    shortsLogo5Size: "NO LOGO",
  },
  {
    _id: "12",
    value: "yorkshirerl",
    label: "Yorkshire RL",
    initials: "YR",
    sport: "rugby",
    playingDesignBreak: "no",
    tshirtDesignBreak: "no",
    numberBreak: "no",
    color1: "#ffffff",
    color1Ref: 1,
    color2: "#1c355e",
    color2Ref: 5,
    color3: "#238dc1",
    color3Ref: 6,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo8: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo9: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "white",
    },
    shortslogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "67mm x 80mm",
    proLogo2Size: "TBC",
    proLogo3Size: "TBC",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "NO LOGO",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "NO LOGO",
    proLogo9Size: "NO LOGO",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "NO LOGO",
    proLogo13Size: "NO LOGO",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "NO LOGO",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "TBC",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "TBC",
    outerLogo4Size: "TBC",
    shortsLogo2Size: "NO LOGO",
    shortsLogo3Size: "NO LOGO",
    shortsLogo4Size: "1NO LOGO",
    shortsLogo5Size: "NO LOGO",
  },
  {
    _id: "13",
    value: "lancashirerl",
    label: "Lancashire RL",
    initials: "LA",
    sport: "rugby",
    playingDesignBreak: "no",
    tshirtDesignBreak: "no",
    numberBreak: "no",
    color1: "#ce0e2d",
    color1Ref: 13,
    color2: "#1c355e",
    color2Ref: 1,
    color3: "#fde021",
    color3Ref: 11,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo7: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo8: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo9: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    outerlogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "white",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "67mm x 80mm",
    proLogo2Size: "TBC",
    proLogo3Size: "TBC",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "NO LOGO",
    proLogo7Size: "NO LOGO",
    proLogo8Size: "NO LOGO",
    proLogo9Size: "NO LOGO",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "NO LOGO",
    proLogo12Size: "NO LOGO",
    proLogo13Size: "NO LOGO",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "NO LOGO",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "TBC",
    tshirtLogo6Size: "NO LOGO",
    outerLogo2Size: "TBC",
    outerLogo4Size: "TBC",
    shortsLogo2Size: "NO LOGO",
    shortsLogo3Size: "NO LOGO",
    shortsLogo4Size: "1NO LOGO",
    shortsLogo5Size: "NO LOGO",
  },
  {
    _id: "14",
    value: "coventry",
    label: "Coventry Rugby",
    initials: "CR",
    sport: "rugby",
    playingDesignBreak: "rectangle",
    tshirtDesignBreak: "square",
    numberBreak: "no",
    color1: "#1c355e",
    color1Ref: 4,
    color2: "#ffffff",
    color2Ref: 1,
    color3: "#1c355e",
    color3Ref: 7,
    alllogo1: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo3: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo6: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "purple",
      pink: "purple",
      yellow: "yellow",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo7: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    playinglogo8: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "orange",
      green: "white",
      red: "white",
    },

    playinglogo9: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo10: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo12: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    playinglogo13: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    playinglogo14: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    playinglogo15: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    traininglogo13: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    traininglogo15: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    tshirtlogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    tshirtlogo6: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "orange",
      green: "white",
      red: "white",
    },

    outerlogo2: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "orange",
      green: "white",
      red: "white",
    },
    outerlogo4: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },
    shortslogo3: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo4: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    shortslogo5: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },
    trainingshortslogo2: {
      white: "white",
      black: "black",
      blue: "black",
      purple: "black",
      pink: "black",
      yellow: "white",
      orange: "white",
      green: "black",
      red: "black",
    },

    none: {
      white: "white",
      black: "white",
      blue: "white",
      purple: "white",
      pink: "white",
      yellow: "white",
      orange: "white",
      green: "white",
      red: "white",
    },

    allLogo1Size: "70mm x 80mm",
    proLogo2Size: "78mm x 70mm",
    proLogo3Size: "45.4mm x 55mm",
    proLogo4Size: "NO LOGO",
    proLogo5Size: "NO LOGO",
    proLogo6Size: "238mm x 105mm",
    proLogo7Size: "44mm x 33mm",
    proLogo8Size: "141mm x 60mm",
    proLogo9Size: "NO LOGO",
    proLogo10Size: "NO LOGO",
    proLogo11Size: "316mm x 285mm",
    proLogo12Size: "NO LOGO",
    proLogo13Size: "70mm x 80mm",
    proLogo14Size: "NO LOGO",
    proLogo15Size: "70mm x 80mm",
    trainingLogo13Size: "NO LOGO",
    trainingLogo15Size: "NO LOGO",
    tshirtLogo2Size: "45.4mm x 55mm",
    tshirtLogo6Size: "155mm x 160mm",
    outerLogo2Size: "67mm x 70mm",
    outerLogo4Size: "80mm x 19.8mm",
    shortsLogo2Size: "45.4mm x 55mm",
    shortsLogo3Size: "NO LOGO",
    shortsLogo4Size: "NO LOGO",
    shortsLogo5Size: "NO LOGO",
  },
];

module.exports = clubs;
