export const COLLECTIONS_LIST_REQUEST = "COLLECTIONS_LIST_REQUEST";
export const COLLECTIONS_LIST_SUCCESS = "COLLECTIONS_LIST_SUCCESS";
export const COLLECTIONS_LIST_FAIL = "COLLECTIONS_LIST_FAIL";

export const COLLECTIONS_CREATE_REQUEST = "COLLECTIONS_CREATE_REQUEST";
export const COLLECTIONS_CREATE_SUCCESS = "COLLECTIONS_CREATE_SUCCESS";
export const COLLECTIONS_CREATE_FAIL = "COLLECTIONS_CREATE_FAIL";

export const COLLECTIONS_UPDATE_REQUEST = "COLLECTIONS_UPDATE_REQUEST";
export const COLLECTIONS_UPDATE_SUCCESS = "COLLECTIONS_UPDATE_SUCCESS";
export const COLLECTIONS_UPDATE_FAIL = "COLLECTIONS_UPDATE_FAIL";

export const COLLECTIONS_DELETE_REQUEST = "COLLECTIONS_DELETE_REQUEST";
export const COLLECTIONS_DELETE_SUCCESS = "COLLECTIONS_DELETE_SUCCESS";
export const COLLECTIONS_DELETE_FAIL = "COLLECTIONS_DELETE_FAIL";
