export const GARMENTS_LIST_REQUEST = "GARMENTS_LIST_REQUEST";
export const GARMENTS_LIST_SUCCESS = "GARMENTS_LIST_SUCCESS";
export const GARMENTS_LIST_FAIL = "GARMENTS_LIST_FAIL";

export const GARMENTS_CREATE_REQUEST = "GARMENTS_CREATE_REQUEST";
export const GARMENTS_CREATE_SUCCESS = "GARMENTS_CREATE_SUCCESS";
export const GARMENTS_CREATE_FAIL = "GARMENTS_CREATE_FAIL";

export const GARMENTS_UPDATE_REQUEST = "GARMENTS_UPDATE_REQUEST";
export const GARMENTS_UPDATE_SUCCESS = "GARMENTS_UPDATE_SUCCESS";
export const GARMENTS_UPDATE_FAIL = "GARMENTS_UPDATE_FAIL";

export const GARMENTS_DELETE_REQUEST = "GARMENTS_DELETE_REQUEST";
export const GARMENTS_DELETE_SUCCESS = "GARMENTS_DELETE_SUCCESS";
export const GARMENTS_DELETE_FAIL = "GARMENTS_DELETE_FAIL";
